server:
  port: 8088
spring:
  # 设置上传文件的大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 931775308
      max-request-size: 1000MB
  profiles:
    active: enc
sust-cloud:
  recycle:
    time: 72


#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    name:
#    password:
#    type:
#    url:
#    username:
#
#obs:
#  sust-cloud:
#    ak:
#    sk:
#    bucketname:
#    endpoint:
